import { Meta, StoryObj } from '@storybook/react-vite';
import { ReactElement } from '../../../node_modules/react';
import { Icon } from './icon';
declare const meta: Meta<typeof Icon>;
export default meta;
type Story = StoryObj<typeof meta>;
export declare const IconPlain: () => ReactElement;
export declare const IconWithBackground: () => ReactElement;
export declare const NavigationIcons: () => ReactElement;
export declare const StatusIcons: () => ReactElement;
export declare const SocialSharingIcons: () => ReactElement;
export declare const CommunicationIcons: () => ReactElement;
export declare const NumberIcons: () => ReactElement;
export declare const DocumentIcons: () => ReactElement;
export declare const FinancialProductsServicesAndConceptIcons: () => ReactElement;
export declare const ExpenseIcons: () => ReactElement;
export declare const WebApplicationIcons: () => ReactElement;
export declare const IconWithText: Story;
