import { Meta, StoryObj } from '@storybook/react-vite';
import { default as List } from './list';
declare const meta: Meta<typeof List>;
export default meta;
type Story = StoryObj<typeof meta>;
export declare const Unordered: Story;
export declare const Ordered: Story;
export declare const Unstyled: Story;
export declare const Horizontal: Story;
export declare const Links: Story;
