compressionLevel: mixed

enableGlobalCache: false

enableHardenedMode: true

enableMirror: true

enableOfflineMode: true

enableTelemetry: false

nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.1.1.cjs
