compressionLevel: mixed

enableGlobalCache: false

enableHardenedMode: true

enableMirror: true

enableOfflineMode: false

enableTelemetry: false

nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.2.1.cjs
