import { Meta, StoryObj } from '@storybook/react-vite';
import { Alert } from '../../index';
declare const meta: Meta<typeof Alert>;
export default meta;
type Story = StoryObj<typeof meta>;
export declare const Information: Story;
export declare const InformationWithMessageAndExplanation: Story;
export declare const InformationWithOnlyExplanation: Story;
export declare const InformationWithLinks: Story;
export declare const Success: Story;
export declare const Warning: Story;
export declare const Error: Story;
export declare const InProgress: Story;
export declare const SuccessFieldLevel: Story;
export declare const WarningFieldLevel: Story;
export declare const ErrorFieldLevel: Story;
