import { Meta, StoryObj } from '@storybook/react-vite';
import { SecondaryNav } from './secondary-nav';
declare const meta: Meta<typeof SecondaryNav>;
export default meta;
type Story = StoryObj<typeof meta>;
export declare const BasicMenuNoChildren: Story;
export declare const BasicMenuNoChildrenOneActive: Story;
export declare const MenuWithChildrenNoActive: Story;
export declare const MenuWithChildrenActiveParent: Story;
export declare const MenuWithChildrenActiveChild: Story;
