import { Meta, StoryObj } from '@storybook/react-vite';
import { Table } from '../../index';
declare const meta: Meta<typeof Table>;
export default meta;
type Story = StoryObj<typeof meta>;
export declare const Standard: Story;
export declare const Responsive: Story;
export declare const HorizontalScroll: Story;
export declare const Striped: Story;
export declare const RightAligned: Story;
export declare const Pagination: Story;
export declare const FixedWidth: Story;
export declare const LongCharacterSets: Story;
export declare const ColumnConfig: Story;
