import { Meta, StoryObj } from '@storybook/react-vite';
import { Expandable } from '../../index';
declare const meta: Meta<typeof Expandable>;
export default meta;
type Story = StoryObj<typeof meta>;
export declare const Default: Story;
export declare const PaddedExpandable: Story;
export declare const OpenOnLoad: Story;
export declare const DefaultExpandableGroup: Story;
export declare const Accordion: Story;
