import { Meta, StoryObj } from '@storybook/react-vite';
import { default as Link } from './link';
declare const meta: Meta<typeof Link>;
export default meta;
type Story = StoryObj<typeof meta>;
export declare const Inline: Story;
export declare const Standalone: Story;
export declare const WithIcon: Story;
export declare const Listlink: Story;
export declare const Destructive: Story;
export declare const LinkWithReactRouterLink: Story;
