name: Publish to npm when GH release created

on:
  release:
    types: [created]

permissions:
  contents: read
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Setup Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version: 26
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: |
          corepack enable
          yarn install --immutable --immutable-cache

      - name: Build package
        run: yarn build

      - name: Publish to npm
        run: npm install -g npm@latest && npm publish --access public --provenance
